### ISSUE TITLE
SC Mobile Singapore using MagiskDetector to detect Magisk

### ISSUE THREAD

**Issue by thexile** [vvb2060/MagiskDetector#11]
[SC Mobile Singapore](https://play.google.com/store/apps/details?id=air.app.scb.breeze.android.main.sg.prod) is making use of MagiskDetector to detect Magisk. Anyway to stop (e.g. cease & desist notice) the bank Standard Chartered from using your program?

**Comment by tbertels** [comment]
It's free software, so as long as they're keeping the copyright notice, they're free to use it.

If you're a client and are annoyed by the fact that it prevents you to use Magisk, feel free to let them know and choose a different bank.

**Comment by thexile** [comment]
Can be bypass using [MomoHider](https://github.com/canyie/Riru-MomoHider) with all options enabled.
