### ISSUE TITLE
Magisk 23.0版本

### ISSUE THREAD

**Issue by StriveMario** [vvb2060/MagiskDetector#12]
尝试了一下Magisk 23.0版本好像处理了这些检测, 请问有其他方式可以检测到新版本的Magisk吗? 感谢~

**Comment by vvb2060** [comment]
没有处理

**Comment by vvb2060** [comment]
https://www.coolapk.com/apk/io.github.vvb2060.mahoshojo 这里有更多检测，但是不开源
