### ISSUE TITLE
MagiskDetector Service with android:isolatedProcess="true" not working with intune SDK. 

### ISSUE THREAD

**Issue by pradiptilala** [vvb2060/MagiskDetector#14]
**Describe the bug:**
I have an app which uses intune sdk for android. We want to integrate a service with with android:isolatedProcess="true" for root detection related functionality on our App.
But, android Service with **android:isolatedProcess="true"** not able to work with our App with already integrated Intune SDK.

**We have also tried to create an separate sample App with intune and with a service having set android:isolatedProcess in Manifest. But this service is not working.**

**To Reproduce**

1.  Create a sample app with service having set android:isolatedProcess in Manifest. Decleration in manifest is as below:
```
 <service
            android:name=".RemoteService"
            android:useAppZygote="true"
            android:isolatedProcess="true" />
```
2. We are using bindService method to bind to the service. As shown below:
```
Intent intent = new Intent(this,IsolatedService.class);
        /*Binding to an isolated service */
        getApplicationContext().bindService(intent, mIsolatedServiceConnection, BIND_AUTO_CREATE);
```
3. When running this sample, it is able to connect to isolated process and onServiceConnected() method of ServiceConnection is called.
4. Then we have integrated the intune library with this App.
5. When running sample app after integrating intune SDK, it is not able to run the service having set android:isolatedProcess.
You can integrate Intune sdk and can check with these existing app which have isolated process to check this scenario: [MagiskDetector](https://github.com/vvb2060/MagiskDetector)
OR
[DetectMagiskHide](https://github.com/darvincisec/DetectMagiskHide)

**Expected behavior:**
It's expected that service with android:isolatedProcess flag set work normally with App which have already Intune SDK integrated. Isolated process do work with intune SDK for Android App.

We have also posted issue with Intune SDK team : https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/76

**Comment by vvb2060** [comment]
Isolated processes do not have any permissions, including network permissions. You should use other ways to integrate the detection in the isolated process into the business. For example, put some critical computational tasks into isolated process and then get the results on the client side and send them to the server.

**Comment by pradiptilala** [comment]
@vvb2060
Yes you are right,
Please find more insight to our issue:

Isolated process used in MagiskDetector App is working as expected.
But after integrating Intune SDK to MagiskDetector demo App, the used Isolated process not able to start/run. We are not getting any log for the same. We have also tested the same scenario on 2 devices Redmi Note 3(Android M) & POCO F1 (Android 10). We have some of the questions and not sure why there is such unexpected behavior.

**Could you please guide us with below questions so that it can help us to get more insight?**
1. Is there any other way to check for Magisk presence without using the isolated process ?
2. Is there any workaround to use isolated process with Intune SDK ?
3. What could be the reason that isolated process is not working with Intune SDK ?
4. Can you help us find out in which conditions, isolated process will not run/work ? 

**You can find more description here on Intune SDK functionality at App build time:**
At Android app build time, Intune SDK will replace Android base classes (Ex. android.app.Activity, android.app.Application) with their respective MAM equivalents (Ex. MAMActivity, MAMApplication) in order to enable Intune management.
**Reference :** [Intune SDK](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android)

**Comment by vvb2060** [comment]
If the isolated service does not start, or if the application does not receive the binder sent by the isolated service, pardon me for not being able to do anything about it. You need to ask Microsoft Intune SDK why disallowed the start of the isolated service.

**Comment by vvb2060** [comment]
I guess there is some detection in the `application` class, like uid, and when the uid is not normal, the process crashes. Since there is no source code and you have not provided logs, I stop the discussion.

**Comment by vvb2060** [comment]
It is also possible that there is a read file behavior in the `application` class, isolated process does not have permission to read the files under `/data/`.

**Comment by pradiptilala** [comment]
I am extremely thankful for your reply. I cannot share the source and logs here.

Coming back to your question, We are not getting any crash log for isolated process. We have put log in each callback method of the ServiceConnection class but not received any of them. We are not able to find what could be the reason whether isolated service is not starting or not able to communicate with isolated process after it start.

> I guess there is some detection in the `application` class, like uid, and when the uid is not normal, the process crashes. Since there is no source code and you have not provided logs, I stop the discussion.

**Comment by vvb2060** [comment]
logcat -b crash -d

**Comment by pradiptilala** [comment]
Thanks for your reply,
Currently we are using Android studio logcat to check Application log. We will try your suggestion to get logs and check if we can get more detailed logs.

**Comment by pradiptilala** [comment]
Thanks for your reply @vvb2060 
I have tried command `logcat -b crash -d` but its returning nothing. Please help me with this.

> logcat -b crash -d
