### ISSUE TITLE
got wrong result after just repack momo

### ISSUE THREAD

**Issue by b14aa178** [vvb2060/MagiskDetector#9]
hi, i tested momo under non-rooted Android 10, Oneplus 5T. and i just repacked momo use tools like xpatch.

it is design behaiver or bug ?

![1](https://user-images.githubusercontent.com/4250419/113660540-e7bca600-96d6-11eb-8a97-46b7376ac640.png)

**Comment by vvb2060** [comment]
只看环境损坏即可。附加说明只是写出最常见的情况，像签名验证失败也会这样。

**Comment by b14aa178** [comment]
不过我注意到在不解决签名问题时momo会明确给出签名验证失败的结果，这就让人有点摸不着头脑了...

**Comment by vvb2060** [comment]
最低级的签名检测失败会显示明确结果，高级检测不显示具体原因以防止分析。
